version: '3.8'

services:
  db:
    container_name: db_dev
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgres/data